// <auto-generated />
namespace TrashPickup.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class chooseday2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(chooseday2));
        
        string IMigrationMetadata.Id
        {
            get { return "201703282253228_choose day2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
